from pathlib import Path

BUNDLE_DIR = Path(__file__).resolve().parent
ASSETS_DIR = BUNDLE_DIR / "unet_assets"
OUTPUTS_DIR = BUNDLE_DIR / "output"
SIM_META_PATH = ASSETS_DIR / "meta.csv"

WEIGHTS_PATH = ASSETS_DIR / "best.weights.h5"
NORM_PATH = ASSETS_DIR / "norm.json"
REFERENCE_FIELD_PATH = ASSETS_DIR / "reference_field.npz"

INPUT_MODE = "3ch"
RASTER_MODE = "line"
LINE_THICKNESS = 2
COARSE_SIGMA = 0.9
BASE_CH = 64
OUT_SCALE = 1.0
USE_RESIDUAL_ON_COARSE = False
RESIDUAL_ALPHA_INIT = 1e-3

ACTUAL_PIXEL_SIZE_UM = 0.325
ACTUAL_FPS = 25.0
DT_OBS = 1.0 / ACTUAL_FPS
MA_WINDOW = 7
ACTUAL_IMAGE_WIDTH_PX = 2304
ACTUAL_IMAGE_HEIGHT_PX = 2304

MIN_CONSEC_FRAMES = 2
MIN_ROWS_AFTER_FILTER = 2
STEP_MAD_K = None
UV_MAD_K = None
OUTLIER_ACTION = "none"

FRAME_STRIDE = 1
MAX_POINTS_PER_FILE = None
N_PARTICLES_TARGET = None

PARTICLE_SAMPLE_MODE = "all"
PARTICLE_GRID_NX = 8
PARTICLE_GRID_NY = 8
PREFER_LONGER_TRAJ = True

VELOCITY_UNIT_MODE = "pixel_size"
PIXEL_SIZE_X_METERS = ACTUAL_PIXEL_SIZE_UM * 1e-6
PIXEL_SIZE_Y_METERS = ACTUAL_PIXEL_SIZE_UM * 1e-6
SWAP_XY = False
FLIP_Y = True
MANUAL_X_SCALE = 1.0
MANUAL_Y_SCALE = 1.0
MANUAL_X_OFFSET = 0.0
MANUAL_Y_OFFSET = 0.0
CLIP_POS_TO_REFERENCE_DOMAIN = True
POSITION_ALIGN_MODE = "physical_meta"

RANDOM_SEED = 40
QUIVER_STRIDE_SC = 8
QUIVER_STRIDE_AC = 12
